#############################################################################
# Dockerfile to build php-fpm image 
# Based on yesops/nginx image                                         
#############################################################################


## Set the base image to Ubuntu
FROM yesops/php5-nginx

## File Author / Maintainer
MAINTAINER Thiago Cangussu <cng.thg@gmail.com>

## Add files
ADD echo.php /usr/share/nginx/html/echo.php
