#############################################################################
# Dockerfile to build gulp image
# Based on yesops/nodejs image
#############################################################################


## Set the base image to yesops/nodejs
FROM yesops/nodejs

## File Author / Maintainer
MAINTAINER Thiago Cangussu <cng.thg@gmail.com>

## Your settings go here:

## Install gulpjs globally:
RUN npm i -g gulp
