#############################################################################
# Dockerfile to build gulpjs image
# Based on yesops/nodejs:trusty image
#############################################################################


## Set the base image to yesops/nodejs-buildpack
FROM yesops/nodejs-buildpack

## File Author / Maintainer
MAINTAINER Thiago Cangussu <cng.thg@gmail.com>

## Install gulpjs globally:
RUN npm i -g gulp
