#############################################################################
# Dockerfile to build gulpjs image
# Based on yesops/nodejs:trusty image
#############################################################################


## Set the base image to yesops/nodejs
FROM yesops/nodejs:trusty

## File Author / Maintainer
MAINTAINER Thiago Cangussu <cng.thg@gmail.com>

## Your settings go here:

## Install gulpjs globally:
RUN npm i -g gulp
